### ISSUE TITLE
Unable to find file

### ISSUE THREAD

**Issue by carmas123** [CodeOTR/flutter_fast_cli#1]
Hi when I try to run `fast` to create a new project on Windows machine I got an error on `flutter create` command.
I got "Unable to find specified file", it would appear as if the `args` package can't find flutter on my PC.

Is there anything particular I can check?

**Comment by carmas123** [comment]
I've created a pull request https://github.com/CodeOTR/flutter_fast_cli/pull/2

**Comment by jtmuller5** [comment]
Thanks! Will get this merged ASAP.

And sorry, I have a mac so windows is hard for me to test

**Comment by jtmuller5** [comment]
Merged, thanks again
